# Site Configuration

# Theme, mapped to the directory: ./theme/xxxx
theme: default

# HTML Language setting
lang: "zh-TW"

# Plugins, implemented in ./plugins/PLUGIN_NAME
# Use {{ vars.PLUGIN_NAME }} in the settings below

# The output of the plugin can be used below, e.g., {{vars.MediumFollowersCountPlugin}}
plugins:
  # Automatically fetch Medium follower count
  - MediumFollowersCountPlugin:
      username: zhgchgli
  # Automatically fetch Github repo star count
  - GithubRepoStarsCountPlugin:
      - ZhgChgLi/ZMarkupParser
      - ZhgChgLi/ZReviewTender
      - ZhgChgLi/ZMediumToMarkdown
      - ZhgChgLi/linkyee

# Google Analytics tracking id
google_analytics_id: G-7QV45ZMJ19

# HTML Title
title: "Misaka Sarina (aka Baker Siacone)"

# Avatar image path
avatar: "https://scontent-tpe1-1.xx.fbcdn.net/v/t39.30808-6/591506397_703540759493044_7714819386948551126_n.jpg?stp=dst-jpg_s960x960_tt6&_nc_cat=108&cb2=99be929b-a592a72f&ccb=1-7&_nc_sid=cc71e4&_nc_ohc=FhjeRiwzrdIQ7kNvwEvkMqE&_nc_oc=AdlNJ_b1tFzzbs5WSJ8z7g_2mYrlQTctb7dRhFR05v1NMjEhNaYJQ00lJQQIodwr4xQXdEgxhJN7K6nkZsudQRRw&_nc_zt=23&_nc_ht=scontent-tpe1-1.xx&_nc_gid=8hjTdG7Fji-KX62vOH4nAA&oh=00_AfkNk13jEOko5Ey44bmih6gGCJbFzOPOIJb9bB0aL0slRg&oe=693FF95C"

# Name section text
name: "Misaka Sarina （aka Baker Siacone）"

# Tagline section text
tagline: >-
    Ianas-Baker C. Siacone aka Misaka Sarina / music producer MAIL2ME:MSarina@siacone.art

# List of links
# icon: Use Font Awesome icons (https://fontawesome.com/search?o=r&m=free)
# text: The displayed text for the link
# title: The url title
# url: The URL of the link
# alt: Alternative text for accessibility
# target: `_blank` opens in a new tab, `_self` opens in the same frame
links:
  - link:
      icon: "fa-solid fa-mug-saucer"
      text: "Buy me a Ko-Fi"
      url: "https://ko-fi.com/misakasarina"
      title: "Buy me a Ko-Fi"
      alt: "Buy me a Ko-Fi"
      target: "_blank"
  - link:
      icon: "fa-brands fa-spotify"
      text: "我的Spotify"
      url: "https://open.spotify.com/artist/7HO1a8ZvIIRGG0y4sjkwy1"
      title: "我的Spotify"
      alt: "我的Spotify"
      target: "_blank"
  - link:
      icon: "fa-solid fa-v"
      text: "我的VocaDB"
      url: "https://vocadb.net/Ar/75285"
      title: "我的VocaDB"
      alt: "我的VocaDB"
      target: "_blank"
  - link:
      icon: "fa-solid fa-angle-right"
      text: "我的Soun<u>dB</u>etter"
      url: "https://soundbetter.com/profiles/701882-misaka-sarina"
      title: "我的Soun<u>dB</u>etter"
      alt: "我的Soun<u>dB</u>etter"
      target: "_blank"
  - link:
      icon: "fa-brands fa-facebook-f"
      text: "我的FB個人主頁"
      url: "https://www.facebook.com/BakerSiacone/"
      title: "我的FB個人主頁"
      alt: "我的FB個人主頁"
      target: "_blank"
  - link:
      icon: "fa-brands fa-facebook-f"
      text: "我的FB粉專"
      url: "https://www.facebook.com/misakasarina/"
      title: "我的FB粉專"
      alt: "我的FB粉專"
      target: "_blank"
  - link:
      icon: "fa-brands fa-facebook-f"
      text: "我的FB社團"
      url: "https://www.facebook.com/share/g/17WHMr54Qj/"
      title: "我的FB社團"
      alt: "我的FB社團"
      target: "_blank"
  - link:
      icon: "fa-brands fa-instagram"
      text: "我的INS個人主頁"
      url: "https://www.instagram.com/bakersiacone/"
      title: "我的INS個人主頁"
      alt: "我的INS個人主頁"
      target: "_blank"
  - link:
      icon: "fa-brands fa-bluesky"
      text: "我的BLUESKY"
      url: "https://bsky.app/profile/msarina.bluesky.siacone.art"
      title: "我的BLUESKY"
      alt: "我的BLUESKY"
      target: "_blank"
  - link:
      icon: "fa-brands fa-youtube"
      text: "我的YouTube（BAKER）"
      url: "https://www.youtube.com/@BakerSiacone"
      title: "我的YouTube（BAKER）"
      alt: "我的YouTube（BAKER）"
      target: "_blank"
  - link:
      icon: "fa-brands fa-youtube"
      text: "我的YouTube（SARINA）"
      url: "https://www.youtube.com/@misakasarina"
      title: "我的YouTube（SARINA）"
      alt: "我的YouTube（SARINA）"
      target: "_blank"

# List of social media links
# icon: Use Font Awesome icons (https://fontawesome.com/search?o=r&m=free)
# title: The url title
# url: The URL of the social media link
# alt: Alternative text for accessibility
# target: _blank opens in a new tab, _self opens in the same frame
socials:
  - social:
      icon: "fa-brands fa-facebook-f"
      url: "https://www.facebook.com/misakasarina/"
      title: "我的FB粉專"
      alt: "我的FB粉專"
      target: "_blank"
  - social:
      icon: "fa-brands fa-instagram"
      url: "https://www.instagram.com/bakersiacone/"
      title: "我的INS個人主頁"
      alt: "我的INS個人主頁"
      target: "_blank"
  - social:
      icon: "fa-brands fa-bluesky"
      url: "https://bsky.app/profile/msarina.bluesky.siacone.art"
      title: "我的BLUESKY"
      alt: "我的BLUESKY"
      target: "_blank"
  - social:
      icon: "fa-brands fa-youtube"
      url: "https://www.youtube.com/@misakasarina"
      title: "我的YouTube（SARINA）"
      alt: "我的YouTube（SARINA）"
      target: "_blank"
  - social:
      icon: "fa-solid fa-envelope"
      url: "mailto:msarina@siacone.art"
      title: "Email: msarina@siacone.art"
      alt: "msarina@siacone.art"
      target: "_blank"

# Footer text
footer: >
    MISAKA SARINA AKA BAKER SIACONE @ SIACONE ART

# Footer copyright message
# Linkyee is a 100% free, open-source project—feel free to modify the copyright message as you like. :)
copyright: >
  Powered by <a href="https://github.com/ZhgChgLi/linkyee" target="_blank">linkyee</a>
